#!/usr/bin/env bash
# check_env.sh — read-only doctor for a fastWorkflow dev environment.
# Usage: bash .claude/skills/fastworkflow-build-and-env/scripts/check_env.sh [--collect]
#   --collect  also run `pytest --collect-only` (adds ~15s)
# Prints PASS/WARN/FAIL lines; exit code 1 if any FAIL. Never prints secret VALUES.
# Facts verified 2026-07-09 against v2.22.2 (commit c33b9a5).

set -u
FAILS=0
WARNS=0
pass() { printf 'PASS  %s\n' "$1"; }
warn() { printf 'WARN  %s\n' "$1"; WARNS=$((WARNS+1)); }
fail() { printf 'FAIL  %s\n' "$1"; FAILS=$((FAILS+1)); }

# --- locate repo root (this script lives 3 levels under it) ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
if [[ ! -f "$ROOT/pyproject.toml" ]] || ! grep -q '^name = "fastworkflow"' "$ROOT/pyproject.toml"; then
    echo "FAIL  cannot locate fastworkflow repo root from $SCRIPT_DIR" >&2
    exit 1
fi
echo "repo root: $ROOT"
cd "$ROOT"

# --- 1. venv ---
PY="$ROOT/.venv/bin/python"
if [[ -x "$PY" ]]; then
    VER="$("$PY" -c 'import sys; print("%d.%d.%d" % sys.version_info[:3])')"
    case "$VER" in
        3.11.*|3.12.*|3.13.*) pass ".venv python $VER (pyproject requires >=3.11,<3.14)";;
        *) fail ".venv python $VER outside pyproject constraint >=3.11,<3.14";;
    esac
else
    fail "no .venv/bin/python — create with: python3.12 -m venv .venv && poetry install --all-extras"
    PY=""
fi

# --- 2. editable install + core/extra imports ---
if [[ -n "$PY" ]]; then
    if ls "$ROOT"/.venv/lib/python3.*/site-packages/fastworkflow.pth >/dev/null 2>&1 \
       || "$PY" -m pip show fastworkflow 2>/dev/null | grep -qi '^Editable project location'; then
        pass "fastworkflow installed editable (.pth) — code changes are live"
    else
        warn "fastworkflow not installed editable in .venv (run: poetry install --all-extras)"
    fi
    META_VER="$("$PY" -c 'import importlib.metadata as m; print(m.version("fastworkflow"))' 2>/dev/null || echo none)"
    PROJ_VER="$(grep -m1 '^version = ' pyproject.toml | cut -d'"' -f2)"
    if [[ "$META_VER" != "$PROJ_VER" ]]; then
        warn "dist-info version $META_VER != pyproject $PROJ_VER (stale editable metadata; harmless, trust pyproject)"
    fi
    for MOD in fastworkflow torch transformers dspy; do
        "$PY" -c "import importlib.util as u,sys; sys.exit(0 if u.find_spec('$MOD') else 1)" \
            && pass "core import: $MOD" || fail "core import missing: $MOD (poetry install)"
    done
    "$PY" -c "import importlib.util as u,sys; sys.exit(0 if u.find_spec('datasets') else 1)" \
        && pass "[training] extra present (datasets)" \
        || warn "[training] extra missing — 'fastworkflow train' will NOT train models (pip install '.[training]')"
    SRV_OK=1
    for MOD in fastapi uvicorn fastapi_mcp jwt; do
        "$PY" -c "import importlib.util as u,sys; sys.exit(0 if u.find_spec('$MOD') else 1)" || SRV_OK=0
    done
    [[ $SRV_OK -eq 1 ]] && pass "[server] extra present (fastapi/uvicorn/fastapi_mcp/pyjwt)" \
        || warn "[server] extra incomplete — run_fastapi_mcp + FastAPI tests unavailable (pip install '.[server]')"
fi

# --- 3. secrets provisioning ---
if [[ -f env/.env ]]; then
    pass "env/.env present (tracked model config)"
    if grep -qE '^[[:space:]]*LITELLM_API_KEY|_TOKEN=' env/.env; then
        fail "env/.env appears to contain KEY/TOKEN entries — env/.env is GIT-TRACKED AND PUBLIC. Move them to passwords/.env NOW."
    else
        pass "env/.env contains no key-like entries (correct: keys never go in tracked files)"
    fi
else
    fail "env/.env missing — key-gated tests will skip (see SKILL.md section 3)"
fi
if [[ -f passwords/.env ]]; then
    if grep -qE '^[A-Z_]+=.*(<|your-)' passwords/.env; then
        fail "passwords/.env still has placeholder values (<...> / your-...) — litellm will raise AuthenticationError"
    else
        pass "passwords/.env present with non-placeholder values"
    fi
else
    fail "passwords/.env missing — copy fastworkflow/examples/fastworkflow.passwords.env to passwords/.env and fill in real keys"
fi
if [[ -f .env ]]; then
    pass "root .env present (generated by gen-env.sh; make targets will parse)"
else
    warn "root .env missing — EVERY make target fails at parse time (include ./.env). Bootstrap: ./gen-env.sh"
fi

# --- 4. golden artifact: trained hello_world ---
HW="fastworkflow/examples/hello_world/___command_info"
if [[ -f "$HW/global/threshold.json" && -e "$HW/global/tinymodel.pth" && -e "$HW/global/largemodel.pth" ]]; then
    pass "golden artifact: $HW is trained (4 FastAPI tests depend on it)"
else
    fail "golden artifact missing: $HW — run: fastworkflow train ./fastworkflow/examples/hello_world ./env/.env ./passwords/.env  (~5 min; fix-0hb rule: never let tests wipe it)"
fi
CME="fastworkflow/_workflows/command_metadata_extraction/___command_info"
[[ -d "$CME/global" ]] && pass "internal CME workflow has trained artifacts" \
    || warn "internal CME artifacts missing at $CME — first train of a non-'fastworkflow' path will train CME first"

# --- 5. optional: test collection ---
if [[ "${1:-}" == "--collect" && -n "$PY" ]]; then
    COUNT="$("$PY" -m pytest --collect-only -q 2>/dev/null | grep -oE '^[0-9]+ tests collected' | grep -oE '^[0-9]+' || true)"
    if [[ -n "$COUNT" ]]; then
        pass "pytest collected $COUNT tests (~1803 expected at v3.1.0)"
        [[ "$COUNT" -lt 1400 ]] && warn "collection count unusually low — check for collection errors: $PY -m pytest --collect-only -q"
    else
        fail "pytest collection failed — run: source .venv/bin/activate && python -m pytest --collect-only -q"
    fi
fi

echo
echo "Summary: $FAILS FAIL, $WARNS WARN"
[[ $FAILS -eq 0 ]] || exit 1
